# Generated by Django 4.1.1 on 2023-02-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genqrcode", "0003_qrcode_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="image",
        ),
    ]
